version: "3.7"
services:
  nginx:
    image: nginx:1.21.3
    working_dir: /app
    volumes:
    - ./.docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
    - ./.docker/config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
    - ./.docker/ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:rw
    - ./.docker/ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:rw
    - .:/app:rw
    ports:
      - "1080:80"
      - "1443:443"

  php:
    image: registry.gitlab.com/spagr/dev-stack/php-8.1.1-fpm-nginx-dev:latest
#    build:
#      context: ./.docker/php
#      target: php_base
    working_dir: /app
    volumes:
    - ./.docker/config/php/php.ini:/usr/local/etc/php/php.ini:rw
    - ./:/app:rw

  mysql:
    image: mysql/mysql-server:8.0.26
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: volby
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql:delegated
      - ./.docker/config/mysql/docker.cnf:/etc/my.cnf.d/docker.cnf:rw

  adminer:
    image: adminer:4.8.1-standalone
    environment:
      ADMINER_PLUGINS: tables-filter
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - "18080:8080"