# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Facade\ElectionResultsFacade:
      arguments:
        $pst4FileUrl: '%env(T4_FILE_URL)%'
        $pst4PFileUrl: '%env(T4_P_FILE_URL)%'

    App\DataFixtures\DistrictFixtures:
      arguments:
        $fileUrl: '%env(DISTRICTS_FILE_URL)%'

    App\DataFixtures\MunicipalityFixtures:
      arguments:
        $fileUrl: '%env(MUNICIPALITIES_FILE_URL)%'

    App\DataFixtures\PartyFixtures:
      arguments:
        $fileUrl: '%env(PARTIES_FILE_URL)%'

    App\Handler\FileHandler:
      arguments:
        $varFolder: '%kernel.project_dir%/var'
